name: Build

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Setup Loom cache
        uses: actions/cache@v6
        with:
          path: .gradle/loom-cache
          # Attempts to (somewhat) mirror the cache key of gradle/actions/setup-gradle:
          # https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#cache-key-strategy
          key: ${{ runner.os }}-gradle-loom-cache-${{ hashFiles('gradle/*.versions.toml', '**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-loom-cache-

      - name: Build
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: ./**/build/libs/
